#!/bin/sh

if [ "$#" -eq 0 ]; then
    set -- "$PWD"
fi


# absolute paths
args=""

for arg in "$@"; do
    case "$arg" in
        -*|+[0-9]*)
            args="$args \"$arg\""
            ;;
        /*)
            args="$args \"$arg\""
            ;;
        *)
            args="$args \"$PWD/$arg\""
            ;;
    esac
done

eval "set -- $args"


if emacsclient -n -c "$@" >/dev/null 2>&1; then
    exit 0
fi


echo "Emacs server is not running" >&2
exit 1
